profile: demo

global:
  image:
    registry: docker.io
    pullSecrets: [ ]

  enableAdmin: false

  jwt:
    secretName: "horusec-jwt"

  broker:
    enabled: true
    host: "rabbitmq.queue"
    port: 5672
    secretName: "horusec-broker"

  database:
    host: "postgresql.database"
    port: 5432
    dialect: "postgres"
    sslMode: false
    logMode: false
    secretName: "horusec-database"

  keycloak:
    publicURL: http://keycloak.local/auth
    internalURL: "" # This field is optional. If not filled, the publicURL will be used.
    realm: zup
    otp: false
    clients:
      public:
        id: manager
      confidential:
        id: auth
        secret: c4f2f7b1-478b-4b52-9758-c272b936da8c

components:
  account:
    name: account
    enabled: true
    image:
      registry: docker.io
      repository: horuszup/horusec-account
      tag: v1.2.0
      pullPolicy: IfNotPresent
      pullSecrets: [ ]
    port:
      http: 8003
    ingress:
      enabled: true
      scheme: "http"
      host: "account.local"
      protocols:
        - http
    extraEnv: []

  analytic:
    name: analytic
    enabled: true
    image:
      registry: docker.io
      repository: horuszup/horusec-analytic
      tag: v1.2.0
      pullPolicy: IfNotPresent
      pullSecrets: [ ]
    port:
      http: 8005
    ingress:
      enabled: true
      scheme: "http"
      host: "analytic.local"
      protocols:
        - http
    extraEnv: []

  api:
    name: api
    enabled: true
    image:
      registry: docker.io
      repository: horuszup/horusec-api
      tag: v2.10.0
      pullPolicy: IfNotPresent
      pullSecrets: [ ]
    port:
      http: 8000
    ingress:
      enabled: true
      scheme: "http"
      host: "api.local"
      protocols:
        - http
    extraEnv: []

  auth:
    name: auth
    type: horusec
    enabled: true
    image:
      registry: docker.io
      repository: horuszup/horusec-auth
      tag: v1.7.0
      pullPolicy: IfNotPresent
      pullSecrets: [ ]
    port:
      http: 8006
      grpc: 8007
    ingress:
      enabled: true
      scheme: "http"
      host: "auth.local"
      protocols:
        - http
    extraEnv: []

  manager:
    name: manager
    enabled: true
    image:
      registry: docker.io
      repository: horuszup/horusec-manager
      tag: v1.8.0
      pullPolicy: IfNotPresent
      pullSecrets: [ ]
    port:
      http: 8080
    ingress:
      enabled: true
      scheme: "http"
      host: "manager.local"
      protocols:
        - http
    extraEnv: []
