---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: horusecmanagers.install.horusec.io
spec:
  group: install.horusec.io
  names:
    kind: HorusecManager
    listKind: HorusecManagerList
    plural: horusecmanagers
    singular: horusecmanager
    shortNames:
      - hm
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status defines the observed state of HorusecManager
      jsonPath: .status.conditions[-1:].reason
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HorusecManager is the Schema for the horusecmanagers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of HorusecManager
            properties:
              components:
                properties:
                  account:
                    properties:
                      enabled:
                        type: boolean
                      extraEnv:
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        type: array
                      image:
                        properties:
                          pullPolicy:
                            type: string
                          pullSecrets:
                            items:
                              type: object
                            type: array
                          registry:
                            type: string
                          repository:
                            type: string
                          tag:
                            type: string
                        type: object
                      ingress:
                        properties:
                          enabled:
                            type: boolean
                          host:
                            type: string
                          protocols:
                            items:
                              type: string
                            type: array
                          scheme:
                            type: string
                        type: object
                      name:
                        type: string
                      port:
                        properties:
                          http:
                            type: integer
                        type: object
                    type: object
                  analytic:
                    properties:
                      enabled:
                        type: boolean
                      extraEnv:
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        type: array
                      image:
                        properties:
                          pullPolicy:
                            type: string
                          pullSecrets:
                            items:
                              type: object
                            type: array
                          registry:
                            type: string
                          repository:
                            type: string
                          tag:
                            type: string
                        type: object
                      ingress:
                        properties:
                          enabled:
                            type: boolean
                          host:
                            type: string
                          protocols:
                            items:
                              type: string
                            type: array
                          scheme:
                            type: string
                        type: object
                      name:
                        type: string
                      port:
                        properties:
                          http:
                            type: integer
                        type: object
                    type: object
                  api:
                    properties:
                      enabled:
                        type: boolean
                      extraEnv:
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        type: array
                      image:
                        properties:
                          pullPolicy:
                            type: string
                          pullSecrets:
                            items:
                              type: object
                            type: array
                          registry:
                            type: string
                          repository:
                            type: string
                          tag:
                            type: string
                        type: object
                      ingress:
                        properties:
                          enabled:
                            type: boolean
                          host:
                            type: string
                          protocols:
                            items:
                              type: string
                            type: array
                          scheme:
                            type: string
                        type: object
                      name:
                        type: string
                      port:
                        properties:
                          http:
                            type: integer
                        type: object
                    type: object
                  auth:
                    properties:
                      enabled:
                        type: boolean
                      extraEnv:
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        type: array
                      image:
                        properties:
                          pullPolicy:
                            type: string
                          pullSecrets:
                            items:
                              type: object
                            type: array
                          registry:
                            type: string
                          repository:
                            type: string
                          tag:
                            type: string
                        type: object
                      ingress:
                        properties:
                          enabled:
                            type: boolean
                          host:
                            type: string
                          protocols:
                            items:
                              type: string
                            type: array
                          scheme:
                            type: string
                        type: object
                      name:
                        type: string
                      port:
                        properties:
                          grpc:
                            type: integer
                          http:
                            type: integer
                        type: object
                      type:
                        enum:
                        - horusec
                        - ldap
                        - keycloak
                        type: string
                    type: object
                  manager:
                    properties:
                      enabled:
                        type: boolean
                      extraEnv:
                        items:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                        type: array
                      image:
                        properties:
                          pullPolicy:
                            type: string
                          pullSecrets:
                            items:
                              type: object
                            type: array
                          registry:
                            type: string
                          repository:
                            type: string
                          tag:
                            type: string
                        type: object
                      ingress:
                        properties:
                          enabled:
                            type: boolean
                          host:
                            type: string
                          protocols:
                            items:
                              type: string
                            type: array
                          scheme:
                            type: string
                        type: object
                      name:
                        type: string
                      port:
                        properties:
                          http:
                            type: integer
                        type: object
                    type: object
                type: object
              global:
                properties:
                  broker:
                    properties:
                      enabled:
                        type: boolean
                      host:
                        type: string
                      port:
                        type: integer
                      secretName:
                        type: string
                    type: object
                  database:
                    properties:
                      dialect:
                        type: string
                      host:
                        type: string
                      logMode:
                        type: boolean
                      port:
                        type: integer
                      secretName:
                        type: string
                      sslMode:
                        type: boolean
                    type: object
                  enableAdmin:
                    type: boolean
                  jwt:
                    properties:
                      secretName:
                        type: string
                    type: object
                  keycloak:
                    properties:
                      clients:
                        properties:
                          confidential:
                            properties:
                              id:
                                type: string
                              secret:
                                type: string
                            required:
                            - id
                            - secret
                            type: object
                          public:
                            properties:
                              id:
                                type: string
                            required:
                            - id
                            type: object
                        required:
                        - confidential
                        - public
                        type: object
                      internalURL:
                        type: string
                      otp:
                        type: boolean
                      publicURL:
                        type: string
                      realm:
                        type: string
                    required:
                    - clients
                    - internalURL
                    - publicURL
                    - realm
                    type: object
                type: object
            type: object
          status:
            description: Status defines the observed state of HorusecManager
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
